### ISSUE TITLE
Matrix room version 10 support tracker

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/mikaela.github.io#281]
* Homeservers I care about upgraded to support it (***Synapse 1.64.0*** or ***Dendrite 0.8.7***)
  * [x] tedomum.net ~~for matterbridge~~
  * [x] jae.fi where matterbridge will move once the other servers are done and upgrades happen
      * https://github.com/matrix-org/synapse/issues/11448
  * [x] matrix.org will probably upgrade instantly, possibly even to rc
    * [ ] EMS including, but not limited to, fedora.im & mozilla.org will likely upgrade once it hits stable.
  * [x] pikaviestin.fi is one of my primary accounts
  * [x] pirateriot.net has my git (partially)
   * [x] rose.place (Dendrite)
   * [x] the-apothecary.club
   * [x] poke diasp.in as PirateIRC bridge host ***not waiting for them to upgrade***
   * [ ] Artemislena.eu
   * [x] Janian.de or I will feel bad updating story room
   * [ ] Fairydust.space?
   * [x] Shine.horse?
   * [ ] Sperg.org?

**Comment by Mikaela** [comment]
Note: this issue simultaneously tracks my `_config.yml` and my room upgrades assuming the first condition won't fail.

**Comment by Mikaela** [comment]
There is also `luckyskies.pet` running Catalyst, but all Conduit family are non-blockers for me due to how long they took for room versions 7, 8 and 9.

**Comment by Mikaela** [comment]
Upstream: https://github.com/matrix-org/synapse/issues/13084

**Comment by Mikaela** [comment]
Currently waiting for https://github.com/matrix-org/synapse/commit/ad5761b65cf6a3fe203d8ffc425ed45b3a0a02fa to be tagged and then get into stable release.

**Comment by Mikaela** [comment]
This list still has value.

**Comment by Mikaela** [comment]
All planned rooms have been upgraded, there is no point in tracking the situation further in this repository.
